# Required to avoid a linker error on Windows when building the dylib.
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-lucrt", "-llegacy_stdio_definitions"]
#rustflags = ["-C", "target-feature=+crt-static"]
#rustflags = ["-lntdll"]
#rustflags=["-lucrtd"]
# Uncomment this to enable unstable APIs in web_sys when targetting wasm.
#[target.'cfg(target_family = "wasm")']
#rustflags = "--cfg=web_sys_unstable_apis"
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-lstdc++"
]
[target.x86_64-apple-darwin]
rustflags = [
#  "-lc++abi", 
  "-lc++"
]
linker = "rust-lld"

[target.aarch64-apple-darwin]
rustflags = [
#  "-lc++abi",
  "-lc++"
]
linker = "rust-lld"
